version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 808:80
        labels:
        - traefik.backend=apache
        - traefik.docker.network=traefik_webgateway
        - traefik.frontend.rule=Host:appache.localhost
        - traefik.port=80
        networks:
        - private
        - public
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/www-data/sf4
        depends_on:
          - php

#    mysql:
#        image: mysql
#        command: "--default-authentication-plugin=mysql_native_password"
#        container_name: sf4_mysql
#        volumes:
#            - .docker/data/db:/var/lib/mysql
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: sf4
#            MYSQL_USER: sf4
#            MYSQL_PASSWORD: sf4

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/www-data/sf4
        environment:
          - maildev_host=sf4_maildev
        networks:
        - private
        - public
#        depends_on:
#          - maildev
#          - mysql

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        container_name: sf4_phpmyadmin
#        environment:
#          PMA_HOST: localhost
#          PMA_PORT: 3306
#        ports:
#            - 8080:80
#        links:
#            - mysql

networks:
    private:
    public:
        external:
            name: traefik_webgateway